services:
  - type: web
    name: poetry-mern-backend
    runtime: node
    buildCommand: |
      cd Server
      rm -rf node_modules package-lock.json
      NODE_ENV=production npm install --production
    startCommand: cd Server && node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.20.7
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8083
      - key: MONGODB_URI
        fromDatabase:
          name: poetry-mern-db
          property: connectionString
