services:
  - type: web
    name: poetry-mern-backend
    runtime: node
    rootDirectory: Server
    buildCommand: |
      npm cache clean --force
      rm -rf node_modules package-lock.json
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.20.7
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8083
      - key: MONGODB_URI
        fromDatabase:
          name: poetry-mern-db
          property: connectionString
